import { sql } from 'drizzle-orm'
import {
  boolean,
  check,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core'
import { ITEM_TYPES, LIMITS } from '@sm/shared'

const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType: () => 'bytea',
  toDriver: (value) => Buffer.from(value),
  fromDriver: (value) => new Uint8Array(value),
})

const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' })

export interface StoredKdfParams {
  alg: string
  version: number
  memoryKiB: number
  iterations: number
  parallelism: number
}

/**
 * Everything secret is ciphertext produced in the browser. The server only ever sees ids,
 * ownership, item kind, sizes and timestamps.
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    username: varchar('username', { length: LIMITS.usernameMax }).notNull().unique(),
    /** HMAC of the client's authKey, never the key itself. */
    authHash: bytea('auth_hash').notNull(),
    kdfSalt: bytea('kdf_salt').notNull(),
    kdfParams: jsonb('kdf_params').$type<StoredKdfParams>().notNull(),
    wrappedVkPw: bytea('wrapped_vk_pw').notNull(),
    wrappedVkRec: bytea('wrapped_vk_rec').notNull(),
    recoveryAuthHash: bytea('recovery_auth_hash').notNull(),
    profileEnc: bytea('profile_enc'),
    totpEnabled: boolean('totp_enabled').notNull().default(false),
    totpSecretEnc: bytea('totp_secret_enc'),
    totpPendingEnc: bytea('totp_pending_enc'),
    totpLastStep: integer('totp_last_step').notNull().default(0),
    itemCount: integer('item_count').notNull().default(0),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    lastLoginAt: timestamptz('last_login_at'),
  },
  (t) => [
    check('users_username_format', sql`${t.username} ~ '^[a-z0-9._-]{3,32}$'`),
    check('users_auth_hash_len', sql`octet_length(${t.authHash}) = 32`),
    check('users_recovery_hash_len', sql`octet_length(${t.recoveryAuthHash}) = 32`),
    check('users_kdf_salt_len', sql`octet_length(${t.kdfSalt}) = 16`),
    check('users_item_count_nonneg', sql`${t.itemCount} >= 0`),
  ],
)

export const vaultItems = pgTable(
  'vault_items',
  {
    /** Generated by the client, because the id is part of the encryption context. */
    id: uuid('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    ciphertext: bytea('ciphertext').notNull(),
    version: integer('version').notNull().default(1),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    updatedAt: timestamptz('updated_at').notNull().defaultNow(),
    deletedAt: timestamptz('deleted_at'),
  },
  (t) => [
    check(
      'vault_items_type_valid',
      sql`${t.type} in (${sql.raw(ITEM_TYPES.map((x) => `'${x}'`).join(', '))})`,
    ),
    // 29 bytes is the AES-GCM envelope overhead (version + IV + tag).
    check(
      'vault_items_ciphertext_size',
      sql`octet_length(${t.ciphertext}) between 29 and ${sql.raw(String(LIMITS.maxItemBytes))}`,
    ),
    check('vault_items_version_positive', sql`${t.version} >= 1`),
    index('vault_items_user_updated_idx').on(t.userId, t.updatedAt),
    index('vault_items_user_type_idx')
      .on(t.userId, t.type)
      .where(sql`${t.deletedAt} is null`),
  ],
)

export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Hash of the current refresh token. The token itself is never stored. */
    refreshHash: bytea('refresh_hash').notNull().unique(),
    /** Hash of the previous token, kept so reuse of a rotated token revokes the session. */
    prevRefreshHash: bytea('prev_refresh_hash'),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
    lastUsedAt: timestamptz('last_used_at').notNull().defaultNow(),
    expiresAt: timestamptz('expires_at').notNull(),
    revokedAt: timestamptz('revoked_at'),
  },
  (t) => [
    check('sessions_refresh_hash_len', sql`octet_length(${t.refreshHash}) = 32`),
    index('sessions_user_idx').on(t.userId),
    index('sessions_expires_idx').on(t.expiresAt),
  ],
)

export const rateLimits = pgTable(
  'rate_limits',
  {
    key: text('key').notNull(),
    windowStart: timestamptz('window_start').notNull(),
    count: integer('count').notNull().default(0),
  },
  (t) => [
    primaryKey({ columns: [t.key, t.windowStart] }),
    index('rate_limits_window_idx').on(t.windowStart),
  ],
)
