import { BASE_TOKENS, DEFAULT_ACCENT, RESOLVED_THEMES, allVars, type ResolvedTheme } from './tokens'

const block = (selector: string, scheme: 'light' | 'dark', theme: ResolvedTheme) =>
  `${selector} {\n  color-scheme: ${scheme};\n` +
  Object.entries(allVars(DEFAULT_ACCENT)[theme])
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n') +
  '\n}\n'

/** The static CSS for every theme with the default accent. A test keeps the file in sync. */
export function renderTokenCss(): string {
  const scheme = (t: ResolvedTheme) => (t === 'light' ? 'light' : 'dark')
  return (
    '/* Generated by `pnpm --filter @sm/web tokens` from src/theme/tokens.ts. Do not edit by hand. */\n\n' +
    block(":root,\n:root[data-theme='light']", 'light', 'light') +
    '\n' +
    block(":root[data-theme='dark']", 'dark', 'dark') +
    '\n' +
    block(":root[data-theme='night']", 'dark', 'night') +
    '\n/* Before the theme script has run (or without it), follow the system setting. */\n' +
    '@media (prefers-color-scheme: dark) {\n' +
    block(':root:not([data-theme])', scheme('dark'), 'dark')
      .split('\n')
      .map((l) => (l ? `  ${l}` : l))
      .join('\n') +
    '}\n' +
    (RESOLVED_THEMES.length === Object.keys(BASE_TOKENS).length ? '' : '/* token mismatch */\n')
  )
}
